CREATE TABLE IF NOT EXISTS nhl_season (
    id CHAR(8) PRIMARY KEY,
    all_star_game_in_use BOOLEAN NOT NULL,
    conferences_in_use BOOLEAN NOT NULL,
    divisions_in_use BOOLEAN NOT NULL,
    end_date TIMESTAMP NOT NULL,
    entry_draft_in_use BOOLEAN NOT NULL,
    formatted_season_id VARCHAR(10) NOT NULL,
    minimum_playoff_minutes_for_goalie_stats_leaders INTEGER NOT NULL,
    minimum_regular_games_for_goalie_stats_leaders INTEGER NOT NULL,
    nhl_stanley_cup_owner BOOLEAN NOT NULL,
    number_of_games INTEGER NOT NULL,
    olympics_participation BOOLEAN NOT NULL,
    point_for_ot_loss_in_use BOOLEAN NOT NULL,
    preseason_startdate TIMESTAMP,
    regular_season_end_date TIMESTAMP NOT NULL,
    row_in_use BOOLEAN NOT NULL,
    season_ordinal INTEGER NOT NULL,
    start_date TIMESTAMP NOT NULL,
    supplemental_draft_in_use BOOLEAN NOT NULL,
    ties_in_use BOOLEAN NOT NULL,
    total_playoff_games INTEGER NOT NULL,
    total_regular_season_games INTEGER NOT NULL,
    wildcard_in_use BOOLEAN NOT NULL,
    raw_json JSONB NOT NULL,
    last_updated TIMESTAMP DEFAULT now()
)