CREATE TABLE IF NOT EXISTS nhl_player (
    id INTEGER PRIMARY KEY,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    is_active BOOL NOT NULL,
    current_team_id SMALLINT REFERENCES nhl_team (id),
    current_team_abbrev CHAR(3),
    full_team_name TEXT NOT NULL,
    team_common_name TEXT NOT NULL,
    team_place_name_with_preposition TEXT NOT NULL,
    team_logo TEXT NOT NULL,
    sweater_number SMALLINT,
    position TEXT NOT NULL,
    headshot TEXT NOT NULL,
    hero_image TEXT NOT NULL,
    height_in_inches SMALLINT,
    height_in_centimeters SMALLINT,
    weight_in_pounds SMALLINT,
    weight_in_kilograms SMALLINT,
    birth_date DATE NOT NULL,
    birth_city TEXT NOT NULL,
    birth_state_province TEXT NOT NULL,
    birth_country TEXT NOT NULL,
    shoots_catches TEXT NOT NULL,
    draft_year SMALLINT,
    draft_team_abbreviation CHAR(3),
    draft_round SMALLINT,
    draft_pick_in_round SMALLINT,
    draft_overall_pick SMALLINT,
    player_slug TEXT NOT NULL,
    in_top100_all_time BOOL NOT NULL,
    in_hhof BOOL NOT NULL,
    raw_json JSONB NOT NULL,
    api_cache_endpoint TEXT NOT NULL REFERENCES api_cache (endpoint),
    last_updated TIMESTAMP DEFAULT now()
)