CREATE TABLE IF NOT EXISTS nhl_player (
    id INTEGER PRIMARY KEY,    
    is_active BOOL NOT NULL,
    current_team_id SMALLINT REFERENCES nhl_team(id),
    current_team_abbrev CHAR(3),    
    full_team_name TEXT,    
    team_common_name TEXT,    
    team_place_name_with_preposition TEXT,    
    first_name TEXT NOT NULL,    
    last_name TEXT NOT NULL,
    team_logo TEXT,
    sweater_number SMALLINT,
    position TEXT,
    headshot TEXT,
    hero_image TEXT,
    height_in_inches SMALLINT,
    height_in_centimeters SMALLINT,
    weight_in_pounds SMALLINT,
    weight_in_kilograms SMALLINT,
    birth_date DATE,    
    birth_city TEXT,    
    birth_state_province TEXT,
    birth_country TEXT,
    shoots_catches TEXT,
    draft_year SMALLINT,
    draft_team_abbreviation CHAR(3),
    draft_round SMALLINT,
    draft_pick_in_round SMALLINT,
    draft_overall_pick SMALLINT,
    player_slug TEXT,   
    in_top100_all_time BOOL,    
    in_hhof BOOL,
    raw_json JSONB NOT NULL,
    api_cache_endpoint TEXT NOT NULL REFERENCES api_cache(endpoint),
    last_updated TIMESTAMP DEFAULT now()
)