CREATE TABLE IF NOT EXISTS nhl_player (
    id INTEGER PRIMARY KEY,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    is_active BOOL NOT NULL,
    current_team_id INTEGER REFERENCES nhl_team (id),
    current_team_abbrev CHAR(3),
    full_team_name TEXT,
    team_common_name TEXT,
    team_place_name_with_preposition TEXT,
    team_logo TEXT,
    sweater_number INTEGER,
    position TEXT NOT NULL,
    headshot TEXT NOT NULL,
    hero_image TEXT NOT NULL,
    height_in_inches INTEGER,
    height_in_centimeters INTEGER,
    weight_in_pounds INTEGER,
    weight_in_kilograms INTEGER,
    birth_date DATE NOT NULL,
    birth_city TEXT NOT NULL,
    birth_state_province TEXT,
    birth_country TEXT NOT NULL,
    shoots_catches TEXT,
    draft_year INTEGER,
    draft_team_abbreviation CHAR(3),
    draft_round INTEGER,
    draft_pick_in_round INTEGER,
    draft_overall_pick INTEGER,
    player_slug TEXT NOT NULL,
    in_top100_all_time BOOL NOT NULL,
    in_hhof BOOL NOT NULL,
    raw_json JSONB NOT NULL,
    endpoint TEXT NOT NULL REFERENCES api_cache (endpoint),
    last_updated TIMESTAMPTZ DEFAULT now() NOT NULL
)
