CREATE TABLE IF NOT EXISTS nhl_playoff_series (
    season_id INTEGER NOT NULL REFERENCES nhl_season (id),
    series_letter CHAR(1) NOT NULL,
    series_url TEXT NOT NULL,
    series_title TEXT NOT NULL,
    series_abbreviation TEXT NOT NULL,
    playoff_round INTEGER NOT NULL,
    top_seed_rank INTEGER NOT NULL,
    top_seed_rank_abbreviation TEXT NOT NULL,
    top_seed_wins INTEGER NOT NULL,
    bottom_seed_rank INTEGER NOT NULL,
    bottom_seed_rank_abbreviation TEXT NOT NULL,
    bottom_seed_wins INTEGER NOT NULL,
    winning_team_id INTEGER REFERENCES nhl_team (id),
    losing_team_id INTEGER REFERENCES nhl_team (id),
    top_seed_team_id INTEGER REFERENCES nhl_team (id) NOT NULL,
    top_seed_team_abbrev CHAR(3) NOT NULL,
    top_seed_team_name TEXT NOT NULL,
    top_seed_team_common_name TEXT NOT NULL,
    top_seed_team_place_name_with_preposition TEXT NOT NULL,
    top_seed_team_logo TEXT NOT NULL,
    top_seed_team_dark_logo TEXT NOT NULL,
    bottom_seed_team_id INTEGER REFERENCES nhl_team (id) NOT NULL,
    bottom_seed_team_abbrev CHAR(3) NOT NULL,
    bottom_seed_team_name TEXT NOT NULL,
    bottom_seed_team_common_name TEXT NOT NULL,
    bottom_seed_team_place_name_with_preposition TEXT NOT NULL,
    bottom_seed_team_logo TEXT NOT NULL,
    bottom_seed_team_dark_logo TEXT NOT NULL,
    raw_json JSONB NOT NULL,
    api_cache_endpoint TEXT NOT NULL REFERENCES api_cache (endpoint),
    last_updated TIMESTAMP DEFAULT now(),
    PRIMARY KEY (season_id, series_letter)
)