CREATE TABLE IF NOT EXISTS nhl_shift (
    id INTEGER NOT NULL UNIQUE,
    detail_code INTEGER,
    duration INTERVAL NOT NULL,
    end_time INTERVAL NOT NULL,
    event_description TEXT,
    event_details TEXT,
    event_number INTEGER,
    first_name TEXT NOT NULL,
    game_id INTEGER NOT NULL REFERENCES nhl_game (id),
    hex_value TEXT,
    last_name TEXT NOT NULL,
    period INTEGER NOT NULL,
    player_id INTEGER NOT NULL REFERENCES nhl_player (id),
    shift_number INTEGER NOT NULL,
    start_time INTERVAL NOT NULL,
    team_abbrev TEXT NOT NULL,
    team_id INTEGER NOT NULL REFERENCES nhl_team (id),
    team_name TEXT NOT NULL,
    type_code INTEGER NOT NULL,
    raw_json JSONB NOT NULL,
    endpoint TEXT NOT NULL REFERENCES api_cache (endpoint),
    last_updated TIMESTAMP DEFAULT now() NOT NULL,
    PRIMARY KEY (game_id, player_id, shift_number),
    FOREIGN KEY (game_id, player_id) REFERENCES nhl_roster_spot (game_id, player_id)
)