CREATE TABLE IF NOT EXISTS nhl_playoff_series (
    season_id INTEGER NOT NULL,
    round INTEGER NOT NULL,
    round_abbrev TEXT NOT NULL,
    round_label TEXT NOT NULL,
    series_letter CHAR(1) NOT NULL,
    series_logo TEXT,
    series_logo_fr TEXT,
    needed_to_win INTEGER NOT NULL,
    length INTEGER NOT NULL,
    bottom_seed_team_id INTEGER NOT NULL REFERENCES nhl_team (id),
    bottom_seed_team_name TEXT NOT NULL,
    bottom_seed_team_abbrev TEXT NOT NULL,
    bottom_seed_team_place_name TEXT,
    bottom_seed_team_place_name_with_preposition TEXT,
    bottom_seed_team_conference_name TEXT,
    bottom_seed_team_conference_abbrev TEXT,
    bottom_seed_team_record TEXT NOT NULL,
    bottom_seed_team_series_wins INTEGER NOT NULL,
    bottom_seed_team_division_abbrev TEXT,
    bottom_seed_team_seed INTEGER NOT NULL,
    bottom_seed_team_logo TEXT,
    bottom_seed_team_dark_logo TEXT,
    top_seed_team_id INTEGER NOT NULL REFERENCES nhl_team (id),
    top_seed_team_name TEXT NOT NULL,
    top_seed_team_abbrev TEXT NOT NULL,
    top_seed_team_place_name TEXT,
    top_seed_team_place_name_with_preposition TEXT,
    top_seed_team_conference_name TEXT,
    top_seed_team_conference_abbrev TEXT,
    top_seed_team_record TEXT NOT NULL,
    top_seed_team_series_wins INTEGER NOT NULL,
    top_seed_team_division_abbrev TEXT,
    top_seed_team_seed INTEGER NOT NULL,
    top_seed_team_logo TEXT,
    top_seed_team_dark_logo TEXT,
    series_length INTEGER NOT NULL,
    game_ids INTEGER[] NOT NULL,
    full_coverage_url TEXT,
    raw_json JSONB NOT NULL,
    endpoint TEXT NOT NULL REFERENCES api_cache (endpoint),
    last_updated TIMESTAMP DEFAULT now() NOT NULL,
    PRIMARY KEY (season_id, series_letter),
    FOREIGN KEY (season_id, series_letter) REFERENCES nhl_playoff_bracket_series (season_id, series_letter)
)