CREATE TABLE IF NOT EXISTS nhl_playoff_series_game (
    id INTEGER PRIMARY KEY,
    season_id INTEGER NOT NULL REFERENCES nhl_season (id),
    game_type game_type NOT NULL,
    game_number INTEGER NOT NULL,
    if_necessary BOOL NOT NULL,
    venue_name TEXT NOT NULL,
    neutral_site BOOL NOT NULL,
    start_time_utc TIMESTAMPTZ NOT NULL,
    eastern_utc_offset CHAR(6) NOT NULL,
    venue_utc_offset CHAR(6) NOT NULL,
    venue_timezone TEXT NOT NULL,
    away_team_id INTEGER NOT NULL REFERENCES nhl_team (id),
    away_team_common_name TEXT NOT NULL,
    away_team_place_name TEXT,
    away_team_place_name_with_preposition TEXT,
    away_team_abbreviation CHAR(3) NOT NULL,
    away_team_score INTEGER NOT NULL,
    home_team_id INTEGER NOT NULL REFERENCES nhl_team(id),
    home_team_common_name TEXT NOT NULL,
    home_team_place_name TEXT,
    home_team_place_name_with_preposition TEXT,
    home_team_abbreviation CHAR(3) NOT NULL,
    home_team_score INTEGER NOT NULL,
    game_center_link TEXT NOT NULL,
    period_descriptor_number INTEGER NOT NULL,
    period_descriptor_type period_type NOT NULL,
    period_descriptor_max_regulation_periods INTEGER NOT NULL,
    top_seed_wins INTEGER NOT NULL,
    bottom_seed_wins INTEGER NOT NULL,
    game_outcome_last_period_type period_type NOT NULL,
    series_letter CHAR(1) NOT NULL,
    raw_json JSONB NOT NULL,
    endpoint TEXT NOT NULL REFERENCES api_cache (endpoint),
    last_updated TIMESTAMP DEFAULT now() NOT NULL,
    FOREIGN KEY (season_id, series_letter) REFERENCES nhl_playoff_bracket_series (season_id, series_letter),
    FOREIGN KEY (season_id, series_letter) REFERENCES nhl_playoff_series (season_id, series_letter),
    UNIQUE (season_id, series_letter, game_number)
)